-- DROP TABLE subCategories;
DROP TABLE business_categories;
DROP TABLE businesses;

-- CREATE TABLE subCategories(
--    id           SERIAL8 PRIMARY KEY
--   ,subCategory  VARCHAR(255)
--   ,category_id  INT REFERENCES categories(id)
-- );

CREATE TABLE business_categories(
   id           SERIAL8 PRIMARY KEY
  ,category     VARCHAR(255)
);

CREATE TABLE businesses(
   id           SERIAL8 PRIMARY KEY
  ,category_id  INT REFERENCES business_categories(id)
  -- ,subCategory  VARCHAR(255)
  ,organization VARCHAR(255) NOT NULL
  ,addressLine1 VARCHAR(255)
  ,addressLine2 VARCHAR(255)
  ,addressLine3 VARCHAR(255)
  ,phoneNumber  VARCHAR(225)
  ,url          VARCHAR(255)
);

-- Reduced set of seed data for testing follows (see below for full set):
INSERT INTO business_categories(category) VALUES ('Healthcare and Wellness');
INSERT INTO business_categories(category) VALUES ('Supermarket and Convenience');
INSERT INTO business_categories(category) VALUES ('Hair and Beauty');
INSERT INTO business_categories(category) VALUES ('Food and Drink');
INSERT INTO business_categories(category) VALUES ('Pet Services');
INSERT INTO business_categories(category) VALUES ('Accommodation and Tourism');
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (1,'Chalmers Hospital','Clunie Street','Banff','AB45 1JA','01261 812 567','http://www.nhsgrampian.org');
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (2,'Scotmid','4 Lusylaw Road','Banff','AB45 1EW','01261 818 264','http://www.scotmid.co.uk');
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (3,'Elegant','41 High Street','Banff','AB45 1AN','01261 815 494',NULL);
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (3,'Salon 45','45 High Street','Banff','AB45 1AN','01261 812 021',NULL);
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (4,'Railway Inn','96 North Castle Street','Banff','AB45 1JJ','01261 812 251',NULL);
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (5,'The Banff Pet Shop','7 Low Street','Banff','AB45 1AU','01261 815 420',NULL);
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (5,'Happy Hounds','3 Low Street','Banff','AB45 1AU','07854 716 166',NULL);
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (4,'The Old Moray','29 Shore Street','Macduff','AB44 1TS','01261 832 279',NULL);
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (5,'Deveron Vets','1 Mill Street','Macduff','AB44 1RS','01261 832 666','https://deveronvets.co.uk/contact-us/macduff/');
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (6,'Ritchie Travel','47 Low Street','Banff','AB45 1AU','01261 815 671',NULL);
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (6,'Carmelite House Hotel','30 Low Street','Banff','AB45 1AY','01261 812 152','http://www.carmelitehousehotel.co.uk/');
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (1,'Macduff Medical Practice','100 Duff Street','Macduff','AB44 1PR','01261 833 777','http://www.nhsgrampian.co.uk');
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (2,'Scotmid','153 Duff Street','Macduff','AB44 1PS','01261 832 533','http://www.scotmid.co.uk');
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (3,'Tusk','75 Duff Street','Macduff','AB44 1PR',NULL,NULL);
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (6,'The Knowes Hotel','78 Market Street','Macduff','AB44 1LL','01261 606 101','https://knoweshotelandrestaurant.co.uk/');
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (1,'Lloydspharmacy','157 Duff Street','Macduff','AB44 1PS','01261 832 219','http://www.lloydspharmacy.com');
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (2,'Costcutter','20 Duff Street','Macduff','AB44 1TL','01261 833 364','http://www.costcutter.com');
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (3,'Efes Turkish Barbers','17 Strait Path','Banff','AB45 1AD','01261 498 597',NULL);
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (3,'Tattooed Monkey','43 Duff Street','Macduff','AB44 1QJ','01261 833 055',NULL);
INSERT INTO businesses(category_id,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES (4,'Duff House Tea Room','Duff House','Banff','AB45 3BX',NULL,NULL);


-- Full set of seed data follows (including cat & subCat as strings):
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Healthcare and Wellness',NULL,'Chalmers Hospital','Clunie Street','Banff','AB45 1JA','01261 812 567','http://www.nhsgrampian.org');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Supermarket and Convenience',NULL,'Scotmid','4 Lusylaw Road','Banff','AB45 1EW','01261 818 264','http://www.scotmid.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Hairdressers','Elegant','41 High Street','Banff','AB45 1AN','01261 815 494',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Hairdressers','Salon 45','45 High Street','Banff','AB45 1AN','01261 812 021',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Pubs','Railway Inn','96 North Castle Street','Banff','AB45 1JJ','01261 812 251',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Supermarket and Convenience',NULL,'The Co-operative Food','Bridge Road','Banff','AB45 1HE','01261 815 005','http://www.co-operative.coop/food');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Charity Shop',NULL,'B.A.A.R.K.','43 Low Street','Banff','AB45 1AU','01261 815 373','http://baarkfoundation.org');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Hairdressers','Be Beautiful','4 Low Street','Banff','AB45 1AU','01261 815 779',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Pet Services',NULL,'The Banff Pet Shop','7 Low Street','Banff','AB45 1AU','01261 815 420',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Pet Services','Dog grooming','Happy Hounds','3 Low Street','Banff','AB45 1AU','07854 716 166',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Pubs','The Fife Arms','12 Low Street','Banff','AB45 1AS','01261 818 882','http://fiferestaurant.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Fast Food','Kelly''s Chips','9-11 Low Street','Banff','AB45 1AU','01261 819 966',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Fast Food','Nazma Tandoori Takeaway','13 Low Street','Banff','AB45 1AU','01261 818 829','http://banffnazma.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Professional Services and Banking','Solicitors','Wilson Defence','17 Low Street','Banff','AB45 1AU','01261 819 831',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Other',NULL,'Ladbrokes','16 Low Street','Banff','AB45 1AS','0800 030 4496','http://www.ladbrokes.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'Tuleni','24 Low Street','Banff','AB45 1AS','01261 815 523','http://tulenibanff.co.uk/ladiesfashiontulenibanff.html');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Fast Food','Happy Palace','19 Low Street','Banff','AB45 1AU','01261 815 816','http://www.happy-palace.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'Love for Flowers','26 Low Street','Banff','AB45 1AS','01261 498 040',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Fast Food','Pyramids Take Away','53 Low Street','Banff','AB45 1AU','01261 815 311',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Accommodation and Tourism','Travel Agents','Ritchie Travel','47 Low Street','Banff','AB45 1AU','01261 815 671',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Accommodation and Tourism','Hotels','Carmelite House Hotel','30 Low Street','Banff','AB45 1AY','01261 812 152','http://www.carmelitehousehotel.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Professional Services and Banking','Banks','Bank Of Scotland','29 Low Street','Banff','AB45 1AU','01261 812 150','http://www.bankofscotland.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Tanning','The Tanning & Beauty Company','46 Bridge Street','Banff','AB45 1HB','01261 818 283',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail','Gifts','Oldanu','32 Bridge Street','Banff','AB45 1HB',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Household Goods and Services','Carpets','Bridge Carpets','28 Bridge Street','Banff','AB45 1HB','01261 812 266',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Full service','Indian Garden','27 Bridge Street','Banff','AB45 1HD','01261 812 277','http://www.indiangardenbanff.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Supermarket and Convenience',NULL,'Tesco Metro','Carmelite Street','Banff','AB45 1AF','03456 779 028','http://www.tesco.com');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Garages','ATS Euromaster','Carmelite Street','Banff','AB45 1AF','01261 812 234','http://www.atseuromaster.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Household Goods and Services','Fixtures and Fittings','Grampian Kitchens & Bathrooms','24 Carmelite Street','Banff','AB45 1AF','01261 812 116','http://www.grampiankitchens.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Pubs','The Market Arms','5 High Shore','Banff','AB45 1DB','01261 812 261',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'Bargainland','Carmelite Street','Banff','AB45 1AF',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Professional Services and Banking','Accountants','SBP Accountants & Tax Advisers','9 Carmelite Street','Banff','AB45 1AF','01261 818 521','http://www.sbp-ca.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty',NULL,'My Place','4-6 Carmelite Street','Banff','AB45 1AF','01261 819 999',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Charity Shop',NULL,'Daniels Place','57 Low Street','Banff','AB45 1AU',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Pubs','The Broken Fiddle','9 Strait Path','Banff','AB45 1AD','01261 498 647',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Hairdressers','Tony Wright','11-13 Strait Path','Banff','AB45 1AD','01261 815 364','http://www.tonywrighthairdressing.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail','Clothing','Banff Tailoring Repairs & Alterations','15 Strait Path','Banff','AB45 1AD','01261 818 317',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail','Vintage','The Retro Rooms','12 Strait Path','Banff','AB45 1AD','07856 652 192',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'G Lawrence','21 Strait Path','Banff','AB45 1AD','01261 815 587',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Attractions and Leisure','Public Attractions','Banff Castle','Castle Street','Banff','AB45 1DJ',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Cafes','The Kelpie Café','Castle Street','Banff','AB45 1DJ',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Pubs','Castle Bar','47 Castle Street','Banff','AB45 1DQ','01261 815 068',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Pet Services','Vets','Bellevue Veterinary Group','41-43 Castle Street','Banff','AB45 1DQ','01261 812 168',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink',NULL,'Seafield Bakery','6 Seafield Street','Banff','AB45 1DS','01261 812 733',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Household Goods and Services','Carpets','James Smith & Son','35 Castle Street','Banff','AB45 1DH','01261 812 433','http://www.jsmithcarpetsbanff.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Household Goods and Services','Fixtures and Fittings','DW Home Furnishings','31 Castle Street','Banff','AB45 1DH','01261 818 222',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Accommodation and Tourism','B and Bs','Castleview','27 Castle Street','Banff','AB45 1DH','01261 818 156',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Accommodation and Tourism','B and Bs','Trinity Manse','21 Castle Street','Banff','AB45 1DH','01261 812 244',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink',NULL,'The Real Tandoori','18 Castle Street','Banff','AB45 1DL','01261 818 080',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Professional Services and Banking','Accountants','Atholl Scott','16 Castle Street','Banff','AB45 1DL','01261 815 525','http://www.athollscott.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Professional Services and Banking','Banks','TSB Bank','12 Castle Street','Banff','AB45 1DL','01261 505 999','http://www.tsb.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'Cook''s Neuk','6-8 Castle Street','Banff','AB45 1DL',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Household Goods and Services','Repairs','Trend DIY','6-8 Castle Street','Banff','AB45 1DL','01261 812 987',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Healthcare and Wellness','Pharmacists','Baird''s Chemist and Post Office','11 Castle Street','Banff','AB45 1DH','01261 815 039','http://www.scottthechemistbanff.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Cafes','Baird''s Coffee Shop','11 Castle Street','Banff','AB45 1DH','01261 815 039','http://www.scottthechemistbanff.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Supermarket and Convenience',NULL,'Premier','1 Castle Street','Banff','AB45 1DH','01261 812 239',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Pubs','Central Bar Banff','25-27 Boyndie Street','Banff','AB45 1DY','01261 812 422',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Cafes','Delight Café','10a Boyndie Street','Banff','AB45 1DY','01261 815 553',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Healthcare and Wellness','Dentists','Banff Dental Practice','7a Boyndie Street','Banff','AB45 1DY','01261 812 703',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Barbers','The Barber Shop','7 Boyndie Street','Banff','AB45 1DY',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Professional Services and Banking','Solicitors','A E A Brodie','40 High Street','Banff','AB45 1AJ','01261 812 681',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Nails','Nails by Anna','79 High Street','Banff','AB45 1AN','07794 357 506',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Hairdressers','Hair & Co','81 High Street','Banff','AB45 1AN','01261 818 877',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty',NULL,'Evissa','79 High Street','Banff','AB45 1AN','01261 812 824',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink',NULL,'J G Ross','75 High Street','Banff','AB45 1AN',NULL,'http://www.jg-ross-bakers.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Healthcare and Wellness',NULL,'Duncan & Todd','73 High Street','Banff','AB45 1AN','01224 644 927','http://duncanandtodd.com');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty',NULL,'Glamour Beauty','69 High Street','Banff','AB45 1AN','01261 812 404',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Healthcare and Wellness','Pharmacists','Strachan Pharmacy','69 High Street','Banff','AB45 1AN','01261 812404','http://www.numarkpharmacists.com');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Cafes','Strachan Pharmacy Café','69 High Street','Banff','AB45 1AN','01262 812404',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail','Clothing','M&Co','34 High Street','Banff','AB45 1AN','01261 818162','http://www.mandco.com');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Professional Services and Banking',NULL,'Stewart & Watson','65 High Street','Banff','AB45 1AN','01542 833 255','http://www.stewartwatson.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'John Stewart','63 High Street','Banff','AB45 1AN','01261 812 440','http://www.johnstewartbutchers.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Fast Food','Lighthouse Fish Bar','55-57 High Street','Banff','AB45 1AN','01261 818 184',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Accommodation and Tourism','Hotels','The County Hotel','30 High Street','Banff','AB45 1AE','01261 815 353','http://www.thecountyhotel.com/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Supermarket and Convenience',NULL,'R S McColls','49-53 High Street','Banff','AB45 1AN','01261 812 138',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Barbers','Dawn''s Barber Shop','47 High Street','Banff','AB45 1AN','07855 895 695',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink',NULL,'Home Bakery','39 High Street','Banff','AB45 1AN','01261 812 313',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Healthcare and Wellness',NULL,'I C Andrew','27 High Street','Banff','AB45 1AN','01261 812 326',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Professional Services and Banking',NULL,'Alexander George & Co','25 High Street','Banff','AB45 1AN','01261 815 678',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Attractions and Leisure','Public Attractions','Banff Museum','High Street','Banff','AB45 1AE','01771 622 906',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Education',NULL,'Banff Library','High Street','Banff','AB45 1AE','01261 455752',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Full service','Roma','21 High Street','Banff','AB45 1AN','01261 818 844',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink',NULL,'The Candy Box','15 High Street','Banff','AB45 1AN','01261 815 575',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Cafes','The Coffee Pot','13 High Street','Banff','AB45 1AN','01261 812 742',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'Fones ''n'' PCs','9 High Street','Banff','AB45 1AN','01261 498 082','http://www.fonesnpcs.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'Imagine','27 Low Street','Banff','AB45 1AU','01261 819 885',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Healthcare and Wellness','Dentists','Deveron Dental Laboratory','17 High Street','Banff','AB45 1AN','01261 812 006',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'The Good Sleep Company','24 High Street','Banff','AB45 1AE','01261 819 984',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Supermarket and Convenience',NULL,'Spar','42 Boyndie Street West','Banff','AB45 1EP','01261 812 308','http://www.spar.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'Spotty Bag Shop','13 Old Market Place','Banff','AB45 1GE','01261 815623',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail','Gifts','Market Crafts','5 & 7 Strait Path','Banff','AB45 1AD',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Attractions and Leisure','Public Attractions','Duff House',NULL,'Banff','AB45 3SX','01261 818 181','https://www.historicenvironment.scot/visit-a-place/places/duff-house/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Sports and Recreation','Sports facilities','Duff House Royal Golf Club',NULL,'Banff','AB45 3SX','01261 812 062','http://www.duffhouseroyal.com/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Full service','Resturant 19',NULL,'Banff','AB45 3SX','01261 812 062','http://www.duffhouseroyal.com/restaurant-nineteen');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Accommodation and Tourism','Hotels','Banff Springs Hotel','Golden Knowes Road','Banff','AB45 2JE','01261 812 881','http://thebanffsprings.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Accommodation and Tourism','Hotels','Fife Lodge Hotel','Sandyhill Road','Banff','AB45 1BE','01261 812 436','https://www.fifelodgehotel.com/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Filling stations','Victoria Filling Station','Boyndie Road','Banff','AB45 2JD','01261 812 217',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Fast Food','Crown Chip Shop','2 Lusylaw Road','Banff','AB45 1EW','01261 815 239',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Full service','Rex''s Kitchen','3 Duncan Street','Banff','AB45 1EQ','01261 812 795',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'Meadowlands','83-7 North Castle Street','Banff','AB45 1JJ','01261 818 535',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Cafes','Thread Bear Café','83-7 North Castle Street','Banff','AB45 1JJ','1262818535',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Pubs','The Ship Inn','8 Deveronside','Banff','AB45 1HP','01261 812 620',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty',NULL,'Elysian','8 Quayside','Banff','AB45 1HQ',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail','Vintage','Upcycled Annie','Quayside','Banff','AB45 1HQ',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Healthcare and Wellness','Acupuncturists','Acupuncture Clinic','81 North Castle Street','Banff','AB45 1HX','01261 818 668',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Valeting','MG CarWash','2A North Castle Street','Banff','AB45 1JJ','07784 194 444',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail','Vintage','Lynash Antiques','9 Old Market Place','Banff','AB45 1GE','01261 812 861',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Garages','County Garage','9 Old Market Place','Banff','AB45 1GE','01261 815 750',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Garages','HC Tyres','5 Duncan Street','Banff','AB45 1EQ','01261 818 153',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Hairdressers','Head Start','68 North Castle Street','Banff','AB45 1DL',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Hairdressers','Cutting Edge','63 North Castle Street','Banff','AB45 1DL',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Repairs','Stewart Cheynes','Deveronside','Banff','AB45 1HL','01261 815 777','http://www.stewartcheyne.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Professional Services and Banking','Architects','Mantell Ritchie','27a High Street','Banff','AB45 1AN','01261 812 267',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Hairdressers','Omika','83 Nrth Castle Street','Banff','AB45 1JJ','01261 818 620',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty',NULL,'Kumari Beauty','8 Low Street','Banff','AB45 1AS','07500 919 563',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Sports and Recreation','Golf Courses','Royal Tarlair Golf Club','Buchan Street','Macduff','AB44 1TA','01261 832 897','http://www.royaltarlair.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Filling stations','Gleaner','Union Road','Macduff','AB44 1UD','01261 832 979',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Accommodation and Tourism','Hotels','The Park Hotel','Fife Street','Macduff','AB44 1YA','01261 832 265','http://www.parkhotel-scotland.co.uk/19357.html');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Education',NULL,'Macduff Library','High Street','Macduff','AB44 1PR','01261 833289',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Household Goods and Services','Fixtures and Fittings','West Kitchen Studio','Old Gamrie Road','Macduff','AB44 1GD','01261 833 800','http://www.westkitchenstudio.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Construction and Trades','Construction','Travis Perkins','Old Gamrie Road','Macduff','AB44 1GD','01261 832 247','http://www.travisperkins.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Sports and Recreation','Sports facilities','Macduff Bowling Club','98 Duff Street','Macduff','AB44 1PR',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Healthcare and Wellness',NULL,'Macduff Medical Practice','100 Duff Street','Macduff','AB44 1PR','01261 833 777','http://www.nhsgrampian.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Healthcare and Wellness','Pharmacists','Lloydspharmacy','157 Duff Street','Macduff','AB44 1PS','01261 832 219','http://www.lloydspharmacy.com');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Supermarket and Convenience',NULL,'Scotmid','153 Duff Street','Macduff','AB44 1PS','01261 832 533','http://www.scotmid.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Hairdressers','Tusk','75 Duff Street','Macduff','AB44 1PR',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Fast Food','Salt N Batter','81 Duff Street','Macduff','AB44 1PR','01261 831 881',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Healthcare and Wellness','Dentists','Macduff Dental','52 Duff Street','Macduff','AB44 1LQ','01261 833 525','http://macduffdental.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Accommodation and Tourism',NULL,'Coasters','6 Crook O Ness Street','Macduff','AB44 1TR','01261 832 425',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Attractions and Leisure','Public Attractions','Macduff Marine Aquarium','11 High Shore','Macduff','AB44 1SL','01261 833 369','http://www.macduff-aquarium.org.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'Inshore Fish Supply','2 Market Street','Macduff','AB44 1RJ','01261 832 584',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Full service','Cornerstone Restaurant','1 Market Street','Macduff','AB44 1RJ','01261 498 632',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Accommodation and Tourism','Hotels','The Knowes Hotel','78 Market Street','Macduff','AB44 1LL','01261 606 101','https://knoweshotelandrestaurant.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Fast Food','Dolphin Fish and Chips','8 Skene Street','Macduff','AB44 1RN','01261 831 280','http://www.dolphinfishandchips.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'Fine Things','Low Street','Banff','AB45',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Fast Food','Andy Tang''s Chinese','19 Crook O Ness Street','Macduff','AB44 1QT','01261 832 481',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Fast Food','China Town','2 Crook O Ness Street','Macduff','AB44 1TR','01261 833 922',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Charity Shop',NULL,'Deveron District Age Concern','35 Shore Street','Macduff','AB44 1TS','01261 832 264','https://www.deverondistrictageconcern.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Cafes','The Seafront Cafe & Takeaway','33 Shore Street','Macduff','AB44 1TS','01261 831 017','http://www.theseafrontmacduff.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Construction and Trades',NULL,'A Paterson','31a Shore Street','Macduff','AB44 1TS',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Pubs','The Old Moray','29 Shore Street','Macduff','AB44 1TS','01261 832 279',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty',NULL,'Lyndsey''s','52 Gellymill Street','Macduff','AB44 1TN','01261 833 719',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Professional Services and Banking','Solicitors','Walter Gerard & Co','48 Gellymill Street','Macduff','AB44 1TN','01261 832 491',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Household Goods and Services','General contractors','J & A Ingram','27 Gellymill Street','Macduff','AB44 1TN','01261 832 343',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Accommodation and Tourism','B and Bs','Monica and Martin''s Bed and Breakfast','21 Gellymill Street','Macduff','AB44 1TN',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Supermarket and Convenience',NULL,'Costcutter','20 Duff Street','Macduff','AB44 1TL','01261 833 364','http://www.costcutter.com');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'J & J Porterfield and Post Office','27 Duff Street','Macduff','AB44 1TL',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Charity Shop',NULL,'British Red Cross Shop','1 Duff Street','Macduff','AB44 1TL','01261 832 857','http://www.redcross.org.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Professional Services and Banking',NULL,'Mortgage Advice Company','27 Shore Street','Macduff','AB44 1TX','01261 833 400','http://www.mortgageadvicecompany.com');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Hairdressers','Meraki','Station Brae','Macduff','AB44 1UL','01261 833 880','http://www.merakihairandbeauty.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink',NULL,'Annies Cakery','Station Brae','Macduff','AB44 1UL','01261 831 743','http://anniescakery.uk/contact-us');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'Seaway','Station Brae','Macduff','AB44 1UL','01261 832 877','http://www.seawaygroup.co.uk/index/company-history');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Construction and Trades','General contractors','Coast Bearings','Station Brae','Macduff','AB44 1UL','01261 831 188','http://www.coastbearings.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'The Platform','Station Brae','Macduff','AB44 1UL','01261 832 877','http://www.theplatform-macduff.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Construction and Trades',NULL,'Bucaneer','4 Union Road','Macduff','AB44 1UJ','01261 835199',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare',NULL,'Deveron Coaches','6 Union Road','Macduff','AB44 1UJ','01261 832 912','http://deveroncoaches.com/index.html');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'RNLI','Bankhead Road Harbour','Macduff','AB44 1RD','01261 832 813','https://rnli.org/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Charity Shop',NULL,'Daniels Place','29 Duff Street','Macduff','AB44 1TL','01261 832 572',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Construction and Trades','General contractors','All in House','20 Gellymill Street','Macduff','AB44 1TN','01261 831 628','http://www.allinhouse.com/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail','Carpets','The Garrett','Bath Street','Macduff','AB44 1SA','01261 832 210','http://www.thegarrethomefurnishers.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Construction and Trades',NULL,'Echo Master Marine Store','25 Shore Street','Macduff','AB44 1TX','01261 831 644','http://echomastermarine.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink',NULL,'Deveron Direct','Station Brae','Macduff','AB44 1UL','01261 833 121','http://www.deverondirect.com/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Hairdressers','Belle Ame Hair and Beauty','21 Shore Street','Macduff','AB44 1UB','01261 832 223',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty',NULL,'Cheryl''s Beauty Room','8 Melrose Cresecent','Macduff','AB44 1QX','07980 139 560',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Shopping and Retail',NULL,'BEAT','Old Gamrie Road','Macduff','AB44 1QD','01261 833 661',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Pet Services','Vets','Deveron Vets','1 Mill Street','Macduff','AB44 1RS','01261 832 666','https://deveronvets.co.uk/contact-us/macduff/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Taxis','Harbour Taxi''s',NULL,NULL,NULL,'07977 845 664',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Taxis','Vale Taxi''s',NULL,NULL,NULL,'07756 988 793',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Taxis','Finnies Taxi''s',NULL,NULL,NULL,'07925 226 909',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Taxis','Denny''s Taxi''s',NULL,NULL,NULL,'01261 833 293 / 07757 903 564',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Taxis','dd Taxi''s',NULL,NULL,NULL,'01261 831 163',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Taxis','Malcolm''s Taxi''s',NULL,NULL,NULL,'07756 799 099',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Taxis','AA Taxi''s',NULL,NULL,NULL,'01261 842 437 / 07854 842 221',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Taxis','Portsoy Taxi''s',NULL,NULL,NULL,'01261 843 770',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Taxis','Sonya''s Taxi''s',NULL,NULL,NULL,'07842 698 242',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Taxis','Eco Taxi''s',NULL,NULL,NULL,'01261 498 100',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Taxis','B and G Taxi''s',NULL,NULL,NULL,'07710 589 626',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Attractions and Leisure','Golf Courses','Myrus Golf Centre and Driving Range',NULL,'Macduff','AB44 1RG','01261 818 804','http://www.myrusgolf.co.uk/');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Filling stations','Victoria Filling Station','Boyndie Road','Banff','AB45 2JD','01261 812 217',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Transport and Motorcare','Filling stations','Union Rd Filling Station','18 Union Road','Macduff','AB44 1UJ','01261 832 978',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink',NULL,'The One Pot Stop Food Bar','Links Brae Layby','Banff',NULL,'07756 378 954',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink',NULL,'Aqua Rue','Aquarium Car Park','Macduff',NULL,'07715 954 152',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink',NULL,'Mo and Wendy''s Street Food','Bridge Road','Banff',NULL,'07887 697 544',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Full service','Bridge View Restaurant','13 Old Market Place','Banff','AB45 1GE','01261 815 623',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Cafes','Duff House Tea Room','Duff House','Banff','AB45 3BX',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Cafes','Myrus Coffee Shop',NULL,'Macduff','AB44 1RG','01261 818 804',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink','Cafes','Home Bakery and Bakehoose Coffee Shop','Duff Street','Macduff','AB44 1LX',NULL,NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Food and Drink',NULL,'Deveronside Social Club','Tannery Street','Banff','AB45 1RQ','01261 812 769','www.deveronside.scot');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Education',NULL,'Vanilla Ink The Smiddy','Old Market Place','Banff','AB45 1GE','01261 498 738','www.vanillainkthesmiddy.co.uk');
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Barbers','Efes Turkish Barbers','17 Strait Path','Banff','AB45 1AD','01261 498 597',NULL);
-- INSERT INTO businesses(category,subCategory,organization,addressLine1,addressLine2,addressLine3,phoneNumber,url) VALUES ('Hair and Beauty','Tattoos','Tattooed Monkey','43 Duff Street','Macduff','AB44 1QJ','01261 833 055',NULL);
